# coding: utf-8

"""
    ngDesk_Operations

    ngDesk_Operations

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.application import Application


class TestApplication(unittest.TestCase):
    """ Application unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplication(self):
        """
        Test Application
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.application.Application()
        pass


if __name__ == '__main__':
    unittest.main()
