# coding: utf-8

"""
    ngDesk_Operations

    ngDesk_Operations

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_get_ticket(self):
        """
        Test case for get_ticket

        
        """
        pass

    def test_get_tickets(self):
        """
        Test case for get_tickets

        
        """
        pass

    def test_post_messages(self):
        """
        Test case for post_messages

        
        """
        pass

    def test_post_tickets(self):
        """
        Test case for post_tickets

        
        """
        pass

    def test_put_tickets(self):
        """
        Test case for put_tickets

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
