# coding: utf-8

"""
    ngDesk_Operations

    ngDesk_Operations

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.application import Application
from .models.attachment import Attachment
from .models.server import Server
from .models.technology import Technology
from .models.ticket import Ticket
from .models.ticket_message import TicketMessage
from .models.update_multiple_statuses import UpdateMultipleStatuses
from .models.user import User

# import apis into sdk package
from .apis.default_api import DefaultApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
