# coding: utf-8

"""
    ngDesk_Operations

    ngDesk_Operations

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .application import Application
from .attachment import Attachment
from .server import Server
from .technology import Technology
from .ticket import Ticket
from .ticket_message import TicketMessage
from .update_multiple_statuses import UpdateMultipleStatuses
from .user import User
