# coding: utf-8

"""
    ngDesk_Operations

    ngDesk_Operations

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Server(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'server_id': 'int',
        'display_server_name': 'str'
    }

    attribute_map = {
        'server_id': 'ServerId',
        'display_server_name': 'DisplayServerName'
    }

    def __init__(self, server_id=None, display_server_name=None):
        """
        Server - a model defined in Swagger
        """

        self._server_id = None
        self._display_server_name = None

        if server_id is not None:
          self.server_id = server_id
        if display_server_name is not None:
          self.display_server_name = display_server_name

    @property
    def server_id(self):
        """
        Gets the server_id of this Server.

        :return: The server_id of this Server.
        :rtype: int
        """
        return self._server_id

    @server_id.setter
    def server_id(self, server_id):
        """
        Sets the server_id of this Server.

        :param server_id: The server_id of this Server.
        :type: int
        """

        self._server_id = server_id

    @property
    def display_server_name(self):
        """
        Gets the display_server_name of this Server.

        :return: The display_server_name of this Server.
        :rtype: str
        """
        return self._display_server_name

    @display_server_name.setter
    def display_server_name(self, display_server_name):
        """
        Sets the display_server_name of this Server.

        :param display_server_name: The display_server_name of this Server.
        :type: str
        """

        self._display_server_name = display_server_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Server):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
