# coding: utf-8

"""
    ngDesk_Operations

    ngDesk_Operations

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Technology(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'technology_id': 'int',
        'technology_name': 'str'
    }

    attribute_map = {
        'technology_id': 'TechnologyId',
        'technology_name': 'TechnologyName'
    }

    def __init__(self, technology_id=None, technology_name=None):
        """
        Technology - a model defined in Swagger
        """

        self._technology_id = None
        self._technology_name = None

        if technology_id is not None:
          self.technology_id = technology_id
        if technology_name is not None:
          self.technology_name = technology_name

    @property
    def technology_id(self):
        """
        Gets the technology_id of this Technology.

        :return: The technology_id of this Technology.
        :rtype: int
        """
        return self._technology_id

    @technology_id.setter
    def technology_id(self, technology_id):
        """
        Sets the technology_id of this Technology.

        :param technology_id: The technology_id of this Technology.
        :type: int
        """

        self._technology_id = technology_id

    @property
    def technology_name(self):
        """
        Gets the technology_name of this Technology.

        :return: The technology_name of this Technology.
        :rtype: str
        """
        return self._technology_name

    @technology_name.setter
    def technology_name(self, technology_name):
        """
        Sets the technology_name of this Technology.

        :param technology_name: The technology_name of this Technology.
        :type: str
        """

        self._technology_name = technology_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Technology):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
