# coding: utf-8

"""
    ngDesk_Operations

    ngDesk_Operations

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UpdateMultipleStatuses(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'ticket_uuid': 'list[str]'
    }

    attribute_map = {
        'status': 'Status',
        'ticket_uuid': 'TicketUUID'
    }

    def __init__(self, status=None, ticket_uuid=None):
        """
        UpdateMultipleStatuses - a model defined in Swagger
        """

        self._status = None
        self._ticket_uuid = None

        if status is not None:
          self.status = status
        if ticket_uuid is not None:
          self.ticket_uuid = ticket_uuid

    @property
    def status(self):
        """
        Gets the status of this UpdateMultipleStatuses.

        :return: The status of this UpdateMultipleStatuses.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this UpdateMultipleStatuses.

        :param status: The status of this UpdateMultipleStatuses.
        :type: str
        """

        self._status = status

    @property
    def ticket_uuid(self):
        """
        Gets the ticket_uuid of this UpdateMultipleStatuses.

        :return: The ticket_uuid of this UpdateMultipleStatuses.
        :rtype: list[str]
        """
        return self._ticket_uuid

    @ticket_uuid.setter
    def ticket_uuid(self, ticket_uuid):
        """
        Sets the ticket_uuid of this UpdateMultipleStatuses.

        :param ticket_uuid: The ticket_uuid of this UpdateMultipleStatuses.
        :type: list[str]
        """

        self._ticket_uuid = ticket_uuid

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UpdateMultipleStatuses):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
